name: Pyinstaller

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nltk pyinstaller
    - name: Generate artifacts
      run: |
        pyinstaller --onefile $(git ls-files 'wordle.py')
#    - name: Upload artifacts
#      uses: actions/upload-artifact@v4
#      with:
#        name: wordle
#        path: dist
    - name: Release
      uses: softprops/action-gh-release@v2
#      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*
#    - name: Output artifact URL
#      run: echo 'Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-url }}'
