name: Pyinstaller

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nltk pyinstaller
    - name: Generate artifacts
      run: |
        pyinstaller --onefile $(git ls-files 'wordle.py')
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*
  windows-build:
    runs-on: windows-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nltk pyinstaller
    - name: Generate artifacts
      run: |
        pyinstaller --onefile $(git ls-files 'wordle.py')
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*
  macos-build:
    runs-on: macos-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nltk pyinstaller
    - name: Generate artifacts
      run: |
        pyinstaller --onefile $(git ls-files 'wordle.py')
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*
